extends RefCounted
## The folk's tasks (pass 11), in the order each gives them. Pass 17 (Hank:
## "the guide has... a bunch of quests... in terms of what you would need to do
## next... they should very much so have, like, multiple quest lines, and then
## depending on where you're at with what your gear is, they can kind of
## recommend what to do next. Same thing with the trainer"): each giver's
## tasks run in LINES (a line's next opens when its last is handed in; each
## line is offered alongside the others), and "What next?" (quests/Advice.gd)
## reads the keeper's gear and progress for the one to do first.
##
## goals: {"type", ...}
##   have (id, count, take): items in the satchel (taken on hand-in if take)
##   craft (id, count) · lore (count: carvings read) · house (a home stands)
##   defeat (id: species, count) · kills (count: any beasts) · region (id)
##   visit (id: a place found, once) · deed (id, count: a thing done, counted:
##   "chest:house", "blast", "bred", "ride", "tend", "meal")
##   bones (count: bone heaps searched) · egg (count: taken from nests)
##   hatch · grow (babies raised) · dig · fish · tame (ids: species, count)
##   herd (count: tamed beasts at the keeper's side now)
## Everything done before a task is taken counts too (the keeper's tallies).
## needs: "region:ID" / "species:ID" / "item:ID" / "milestone:ID" the world
## must have (or the keeper must have done) first; "streamed": a pass-16 world
## (the fallen buildings, the bog's lakes). A line waits while its next task's
## needs are unmet.
## reward: {item id: count} ("ancient_coin" is money), and "xp:SKILL" (skill
## XP), "milestone:ID" (something learned: "milestone:learned_bombs") or
## "perk:ID" (a star of the skills, taught outright: SkillStars).

const QUESTS := [
	# Orrin, the Wayfinder: first steps, the wide wilds and the great threats.
	{"id": "guide_timber", "giver": "guide", "line": "guide_start", "title": "Timber and stone",
		"ask": "Before anything else: wood and stone. Take your axe to the trees and your pickaxe to the grey outcrops. Eight logs and six stones will do for a start.",
		"done": "Good. Everything out here starts with a log and a stone. Here: torches, and something for your trouble.",
		"goals": [{"type": "have", "id": "log", "count": 8}, {"type": "have", "id": "stone", "count": 6}], "reward": {"torch": 4, "xp:gathering": 30}},
	{"id": "guide_bench", "giver": "guide", "line": "guide_start", "title": "A bench of your own",
		"ask": "Tools, walls, saddles: it all comes off a workbench. Make one (Tab opens your satchel) and set it down by the fire.",
		"done": "Now you've a proper camp. Keep your bench close: its recipes only work near it.",
		"goals": [{"type": "craft", "id": "workbench", "count": 1}], "reward": {"plank": 6, "ancient_coin": 2}},
	{"id": "guide_tools", "giver": "guide", "line": "guide_start", "title": "Better tools",
		"ask": "Those stone tools won't last. Sky-Fang crystal grows in the rock hereabouts: mine a few shards and make yourself a crystal pickaxe at the workbench.",
		"done": "Now that's a Keeper's pickaxe. Here, torches: the nights are long out here.",
		"goals": [{"type": "craft", "id": "crystal_pickaxe", "count": 1}], "reward": {"torch": 4, "ancient_coin": 3}},
	{"id": "guide_axe", "giver": "guide", "line": "guide_start", "title": "A keener edge",
		"ask": "A crystal pickaxe, and still that stone axe? Put six shards to your axe's edge at the bench. It'll fell a tree in two blows.",
		"done": "Listen to it bite! The skywood won't know what hit it.",
		"goals": [{"type": "craft", "id": "crystal_axe", "count": 1}], "reward": {"ancient_coin": 4, "xp:gathering": 40}},
	{"id": "guide_fire", "giver": "guide", "line": "guide_start", "title": "Fire in the dark",
		"ask": "Raw meat and cold nights will finish a Keeper faster than any rex. Build a campfire and cook yourself something.",
		"done": "Smells like home. A fed Keeper heals, a hungry one doesn't. Remember that.",
		"goals": [{"type": "craft", "id": "campfire", "count": 1}, {"type": "craft", "id": "cooked_meat", "count": 1}], "reward": {"cooked_meat": 3, "ancient_coin": 2}},
	{"id": "guide_armour", "giver": "guide", "line": "guide_start", "title": "Dressed for the wilds",
		"ask": "You're walking about in your shirt. Weave yourself Mossweave armour at the bench: fibre and a few logs. It won't stop a rex, but it'll stop a raptor's first bite.",
		"done": "Better. Now the raptors have to work for it. When you can, trade up: leather, then fang, then crystal.",
		"goals": [{"type": "craft", "id": "moss_chestplate", "count": 1}], "reward": {"ancient_coin": 3, "xp:combat": 30}},
	{"id": "guide_home", "giver": "guide", "line": "guide_start", "title": "Four walls and a roof",
		"ask": "Folk won't settle where there's no shelter. Build a proper house: walls all round, a door, a roof over every tile, a torch and a bed.",
		"done": "A real home! Word travels in the wilds. You'll have neighbours before long.",
		"goals": [{"type": "house", "count": 1}], "reward": {"torch": 6, "ancient_coin": 5}},
	{"id": "guide_carvings", "giver": "guide", "line": "guide_explore", "title": "What the old ones left",
		"ask": "The first builders carved their story into the ruins. Read three of their carvings (E on the stones) and you'll know this land better than I do.",
		"done": "You see it now. The Sky-Fangs, the tribe, the Keepers. You're part of that story whether you like it or not.",
		"goals": [{"type": "lore", "count": 3}], "reward": {"ancient_coin": 6}},
	{"id": "guide_old_places", "giver": "guide", "line": "guide_explore", "title": "Old places", "needs": "streamed",
		"ask": "People lived out here once, before the beasts grew so big. Their houses and inns still stand, half fallen in. Find two and see what they left in their chests.",
		"done": "Somebody's spoons, somebody's coin. They left in a hurry, whoever they were. Keep looking: the wilds are full of such places.",
		"goals": [{"type": "deed", "id": "chest:house", "count": 2}], "reward": {"ancient_coin": 6, "xp:gathering": 40}},
	{"id": "guide_bonelands", "giver": "guide", "line": "guide_explore", "title": "Where the bones lie",
		"ask": "East, past the forest's edge, the crystal took the bones of the old world. Walk the Bonelands and search three bone heaps. See what the sky left behind.",
		"done": "Crystal in the marrow of bones older than the tribe. Something out there was buried, not just dead. Keep your eyes open.",
		"goals": [{"type": "region", "id": "bonelands", "count": 1}, {"type": "bones", "count": 3}], "reward": {"ancient_coin": 10}},
	{"id": "guide_glassmere", "giver": "guide", "line": "guide_explore", "title": "The water to the {dir:glassmere}", "needs": "region:glassmere",
		"ask": "{Dir:glassmere} of here the land sinks into the Mirefen: bog and black water, and at its heart a mere as deep as a well. Go and see it, and mind what swims there.",
		"done": "You saw the islands? The tribe fished from boats out there, once. Maybe you can too.",
		"goals": [{"type": "region", "id": "glassmere", "count": 1}], "reward": {"ancient_coin": 8}},
	{"id": "guide_hoard", "giver": "guide", "line": "guide_explore", "title": "What the lakes keep", "needs": "streamed",
		"ask": "The Mirefen's lakes have islands at their hearts, and the old fishers hid their hoards on them. Wade out, or take a boat, and open one. Mind the sail-backs: they keep those islands.",
		"done": "A hoard from the heart of the lake! You've braver legs than mine.",
		"goals": [{"type": "deed", "id": "chest:treasure", "count": 1}], "reward": {"ancient_coin": 10, "xp:fishing": 40}},
	{"id": "guide_caves", "giver": "guide", "line": "guide_explore", "title": "Under the stone",
		"ask": "There are caves in the wilds: dark mouths in the rock. Take torches and go down into one. The crystal grows thickest where the sun never reaches.",
		"done": "You came back up! Most don't, the first time. There's more down there than rock.",
		"goals": [{"type": "region", "id": "caves", "count": 1}], "reward": {"torch": 6, "ancient_coin": 5}},
	{"id": "guide_sunward", "giver": "guide", "line": "guide_explore", "title": "The Sunward", "needs": "region:dunes",
		"ask": "There are people in the dunes: nomads, the old tribe's cousins. They call themselves the Sunward. Find their oasis and talk to their trader. Don't draw a blade on them.",
		"done": "Traders! Then we're not alone out here. Keep on their good side.",
		"goals": [{"type": "visit", "id": "sunward_oasis", "count": 1}], "reward": {"ancient_coin": 10}},
	{"id": "guide_north", "giver": "guide", "line": "guide_explore", "title": "Into the ash", "needs": "region:pale_hills",
		"ask": "The last Keeper went north, into the Pale Lands, where the ash falls from the burning mountain. No one's seen them since. Cover your face out there. If anyone can find where they went, it's you.",
		"done": "Their camp, still standing... and their journal. Whatever they found up there, it's waiting for you now.",
		"goals": [{"type": "region", "id": "pale_hills", "count": 1}, {"type": "visit", "id": "keeper_camp", "count": 1}], "reward": {"ancient_coin": 20}},
	{"id": "guide_alpha", "giver": "guide", "line": "guide_hunt", "title": "The Shardback's den",
		"ask": "The raptors answer to something big in the north-east. Skarn, the old tribe called it. Until it falls, nowhere's safe. It's marked red on your map.",
		"done": "Skarn, down! The packs will scatter now. The tribe would have sung about this for a month.",
		"goals": [{"type": "defeat", "id": "alpha", "count": 1}], "reward": {"ancient_coin": 15, "prism_crystal": 2}},
	{"id": "guide_ashen", "giver": "guide", "line": "guide_hunt", "title": "The Ashen", "needs": "milestone:alpha",
		"ask": "Raiders came down out of the ash and burned a fisher's camp. The Ashen, they call themselves: skull masks, tamed raptors. Their war camp is in the Pale Lands' east. Bring down their chief.",
		"done": "Their chief, fallen. They'll think twice before they come south again. For a while.",
		"goals": [{"type": "visit", "id": "ashen_chief", "count": 1}], "reward": {"ancient_coin": 25, "trex_scale": 2}},
	{"id": "guide_king", "giver": "guide", "line": "guide_hunt", "title": "The Buried King", "needs": "species:ossuar",
		"ask": "The desert carvings speak of a king of bones, bound with crystal and buried under the sand. The tribe called him Ossuar. They say he wakes if you call him with his own bones. I'd rather he didn't.",
		"done": "Ossuar, laid to rest for good. The bones will sleep easier now. So will I.",
		"goals": [{"type": "defeat", "id": "ossuar", "count": 1}], "reward": {"ancient_coin": 25, "prism_crystal": 4}},
	{"id": "guide_maw", "giver": "guide", "line": "guide_hunt", "title": "The monster in the mere", "needs": "region:glassmere",
		"ask": "Old Maw. The fishers won't say its name out loud. It hunts the deep water of the Mirefen's meres, and it takes boats. Take a boat out, and when it breaches, strike.",
		"done": "Old Maw, beaten! The fishers will sing about you. Badly, but they'll sing.",
		"goals": [{"type": "defeat", "id": "maw", "count": 1}], "reward": {"ancient_coin": 25, "xp:combat": 150}},
	# Pass 18: each land's great boss.
	{"id": "guide_grimjaw", "giver": "guide", "line": "guide_hunt", "title": "The Mire King", "needs": "streamed",
		"ask": "There's something older than Old Maw in the Mirefen. Grimjaw, the fishers call it: a croc as long as a longneck, lying under the water at the bank of the farthest mere. Keep off the water's edge when the ripples come for you.",
		"done": "Grimjaw, dead! Its hide makes a saddle fit for any hunter. Ask the warden: you can ride raptors and rexes now.",
		"goals": [{"type": "defeat", "id": "grimjaw", "count": 1}], "reward": {"ancient_coin": 30, "xp:combat": 200}},
	{"id": "guide_reaper", "giver": "guide", "line": "guide_hunt", "title": "Harrow", "needs": "region:pale_hills",
		"ask": "Deep in the Pale Lands, where the ash lies thickest, there's a hollow ringed with bones. The Ashen won't go near it. Something with scythes for claws keeps it: Harrow, the Pale Reaper. Watch the ground for its shadow when it leaps, and roll through its shriek.",
		"done": "The Reaper's claws... cold as the grave, even now. Bind one into a charm and the volcano's heat will never touch you.",
		"goals": [{"type": "defeat", "id": "reaper", "count": 1}], "reward": {"ancient_coin": 35, "xp:combat": 250}},
	{"id": "guide_stormcrest", "giver": "guide", "line": "guide_hunt", "title": "Queen of the Canopy", "needs": "region:canopy",
		"ask": "Up in the treetops over the jungle's heart there's an eyrie of broken branches and bones. Stormcrest nests there, the greatest thing that flies. When she takes to the sky, the storm comes with her. Watch for the crackle before the lightning.",
		"done": "Stormcrest has fallen! The sky's a little quieter. Her feathers still crackle, look.",
		"goals": [{"type": "defeat", "id": "stormcrest", "count": 1}], "reward": {"ancient_coin": 40, "xp:combat": 300}},
	{"id": "guide_cinder", "giver": "guide", "line": "guide_hunt", "title": "The mountain's heart", "needs": "region:volcano",
		"ask": "In the crater of Embercrack, on the floor beside the lava lake, the Cinderhulk sleeps. An ankylosaur the mountain's fire got into. When it curls into its shell, get back. When the shell cracks, strike.",
		"done": "The Cinderhulk... and its core, still burning. There's nothing in the wilds you haven't faced now, Keeper.",
		"goals": [{"type": "defeat", "id": "cinder", "count": 1}], "reward": {"ancient_coin": 50, "xp:combat": 400, "perk:second_wind": 1}},

	# Pass 18: the far ring (a new world's): the jungle, the treetops, the volcano.
	{"id": "guide_jungle", "giver": "guide", "line": "guide_far", "title": "The Glimmercap", "needs": "region:jungle",
		"ask": "Past the Pale Lands and the bog the jungle begins: trees so tall you can't see their tops, and the crystal in everything. The beasts there glow with it. Go and see it for yourself.",
		"done": "You've seen the giants, then. Keep your eyes on the branches over you: things drop out of them.",
		"goals": [{"type": "region", "id": "jungle", "count": 1}], "reward": {"ancient_coin": 20, "xp:gathering": 80}},
	{"id": "guide_canopy", "giver": "guide", "line": "guide_far", "title": "Up in the canopy", "needs": "region:jungle",
		"ask": "The jungle folk had rope ladders up the giants, and a whole country up there in the branches. Find a ladder and climb, or tame a pteranodon and fly.",
		"done": "The canopy! Bark and branches as wide as roads, and nothing but sky below them. Mind the flyers.",
		"goals": [{"type": "region", "id": "canopy", "count": 1}], "reward": {"ancient_coin": 25, "vine": 6}},
	{"id": "guide_volcano", "giver": "guide", "line": "guide_far", "title": "Embercrack Ridge", "needs": "region:volcano",
		"ask": "Beyond the Pale Lands the ground turns black and the air burns: Embercrack Ridge, the volcano. The heat will cook you if you stay. Find hot springs to cool off, or a charm against it. Bring me obsidian from its rock.",
		"done": "Obsidian! Keener than steel. At an ember forge you could make armour of it that laughs at the heat.",
		"goals": [{"type": "region", "id": "volcano", "count": 1}, {"type": "have", "id": "obsidian", "count": 5, "take": false}], "reward": {"ancient_coin": 30, "emberstone": 2}},

	# Tamsin, the Trader: go out, bring things back.
	{"id": "trader_fossils", "giver": "merchant", "line": "merchant_goods", "title": "Bones of the old world",
		"ask": "Collectors pay a fortune for fossil bones. Dig up relic mounds with a hoe, or pick through bone heaps, and bring me three.",
		"done": "Beautiful. Well, beautifully old. Here's your cut.",
		"goals": [{"type": "have", "id": "fossil_bone", "count": 3, "take": true}], "reward": {"ancient_coin": 12}},
	{"id": "trader_shards", "giver": "merchant", "line": "merchant_goods", "title": "Shards for the market",
		"ask": "Sky-Fang crystal sells in every market from here to the coast. Ten shards, and I'll pay you better than I pay anyone. Don't tell anyone.",
		"done": "Ten shards, ten little stars. Pleasure doing business.",
		"goals": [{"type": "have", "id": "crystal_shard", "count": 10, "take": true}], "reward": {"ancient_coin": 10}},
	{"id": "trader_meal", "giver": "merchant", "line": "merchant_goods", "title": "Somebody's supper", "needs": "streamed",
		"ask": "The old inns out in the wilds: they say some tables are still laid, the food sealed in crocks. Bring me a meal off one of those tables and I'll pay you well for the story.",
		"done": "Still good, after all this time? I'll never understand the old folk's cooking. Here's your coin.",
		"goals": [{"type": "deed", "id": "meal", "count": 1}], "reward": {"ancient_coin": 8}},
	{"id": "trader_bones", "giver": "merchant", "line": "merchant_goods", "title": "A cartload of bones",
		"ask": "There's a bone-carver who'll buy anything from the Bonelands. Twelve old bones from the heaps out east. Big ones.",
		"done": "My poor pack-stego would have loved to carry these. Your coin.",
		"goals": [{"type": "have", "id": "old_bone", "count": 12, "take": true}], "reward": {"ancient_coin": 12}},
	{"id": "trader_fangs", "giver": "merchant", "line": "merchant_goods", "title": "Fangs on a string",
		"ask": "Raptor fangs make lovely necklaces. Lovely, expensive necklaces. Four of them, please.",
		"done": "Fresh! Well, fresh-ish. Here, and keep your fingers.",
		"goals": [{"type": "have", "id": "raptor_fang", "count": 4, "take": true}], "reward": {"ancient_coin": 14}},
	{"id": "trader_scales", "giver": "merchant", "line": "merchant_goods", "title": "Sail-scale", "needs": "item:sail_scale",
		"ask": "The sail-backs in the dunes lie on the warm stones all morning. Their sail-scales hold the sun, they say. Bring me three and I'll show you what a gardener does with them.",
		"done": "Still warm! Here: the pattern for a Sun Sail, and a little something for the walk.",
		"goals": [{"type": "have", "id": "sail_scale", "count": 3, "take": true}], "reward": {"ancient_coin": 12, "sun_sail": 1}},
	{"id": "trader_pearls", "giver": "merchant", "line": "merchant_goods", "title": "Mirefen pearls", "needs": "item:glass_pearl",
		"ask": "The clams on the Mirefen's islands grow pearls, clear as glass for all the black water. You'll need a boat to reach them. Three pearls and I'll make it worth the trip.",
		"done": "Clear as glass! These will fetch a small fortune. Well, a medium fortune. For you: coin.",
		"goals": [{"type": "have", "id": "glass_pearl", "count": 3, "take": true}], "reward": {"ancient_coin": 20}},
	{"id": "trader_cactus", "giver": "merchant", "line": "merchant_goods", "title": "Fruit of the dunes", "needs": "item:cactus_fruit",
		"ask": "Out in the dunes to the {dir:dunes} the cacti fruit red as embers. Sweet as honey, and nobody sells them. Five, please.",
		"done": "Mm! Sticky. Worth every coin. Here.",
		"goals": [{"type": "have", "id": "cactus_fruit", "count": 5, "take": true}], "reward": {"ancient_coin": 12}},
	{"id": "trader_tooth", "giver": "merchant", "line": "merchant_goods", "title": "A tooth from the deep", "needs": "item:maw_tooth",
		"ask": "Fishermen swear there's a monster in the Mirefen's deep mere. Big as a longneck, all teeth. Bring me one of those teeth and I'll believe it.",
		"done": "It's... real. And it's the size of my hand. Here, take all of this before I faint.",
		"goals": [{"type": "have", "id": "maw_tooth", "count": 1, "take": true}], "reward": {"ancient_coin": 30}},
	{"id": "trader_chalk", "giver": "merchant", "line": "merchant_goods", "title": "Pale crystal", "needs": "item:pale_crystal",
		"ask": "Up in the Pale Hills the crystal grows white, not blue. Nobody's ever brought any down. Three pieces and you'll be the first.",
		"done": "White Sky-Fang. I've never seen it. Nobody has. Name your price. No, wait, I'll name it.",
		"goals": [{"type": "have", "id": "pale_crystal", "count": 3, "take": true}], "reward": {"ancient_coin": 25}},

	# Kaya, the Beast-Warden: taming, the young, and riding.
	{"id": "warden_lystro", "giver": "warden", "line": "warden_taming", "title": "A gentle start",
		"ask": "Let's see your hands with a beast. Lystrosaurs are the gentlest things out there: a berry or two and they're yours. Tame one.",
		"done": "Look at it, following you about! That's the start of everything.",
		"goals": [{"type": "tame", "ids": ["lystro"], "count": 1}], "reward": {"berry": 10, "ancient_coin": 3}},
	{"id": "warden_patient", "giver": "warden", "line": "warden_taming", "title": "Patient hands",
		"ask": "The big grazers take patience. Twenty berries, one at a time, stepping back between. Tame a stego, a trike or a longneck.",
		"done": "That's real patience. Most folk get a tail to the face.",
		"goals": [{"type": "tame", "ids": ["stego", "trike", "longneck"], "count": 1}], "reward": {"ancient_coin": 10}},
	{"id": "warden_herd", "giver": "warden", "line": "warden_taming", "title": "A little herd",
		"ask": "One beast is a pet. Three is a herd. Keep three companions at your side at once and they'll start to look after each other.",
		"done": "Look at them, all following you about! Now you're a warden.",
		"goals": [{"type": "herd", "count": 3}], "reward": {"beast_treat": 2, "xp:taming": 60}},
	{"id": "warden_raptor", "giver": "warden", "line": "warden_taming", "title": "The netted hunter",
		"ask": "Now the hard one. Net a raptor, and feed it meat while it's down. Mind its packmates.",
		"done": "A Shardback that trusts you. The old Keepers rode out with packs of them.",
		"goals": [{"type": "tame", "ids": ["raptor"], "count": 1}], "reward": {"net": 4, "ancient_coin": 8}},
	{"id": "warden_parasaur", "giver": "warden", "line": "warden_taming", "title": "Down by the water", "needs": "species:parasaur",
		"ask": "Parasaurs graze the edges of the Mirefen. Listen for them: they trumpet through those crests. Tame one and it'll warn you when a hunter's near.",
		"done": "Hear that call? That's the best alarm in the wilds.",
		"goals": [{"type": "tame", "ids": ["parasaur"], "count": 1}], "reward": {"ancient_coin": 12}},
	{"id": "warden_sand", "giver": "warden", "line": "warden_taming", "title": "Sand and sun", "needs": "region:dunes",
		"ask": "The dunes have beasts of their own. A frill-headed protoceratops, or a sail-backed dimetrodon if you've the nerve. Tame one and bring it home.",
		"done": "A beast of the sand. Watch it: it knows things about that desert we don't.",
		"goals": [{"type": "tame", "ids": ["proto", "dimetrodon"], "count": 1}], "reward": {"ancient_coin": 12}},
	{"id": "warden_allo", "giver": "warden", "line": "warden_taming", "title": "Rust and patience",
		"ask": "An allosaur. Net it, feed it, don't die. If you can tame one of those, you can tame anything out there.",
		"done": "A Rustback at your side. I'd say I'm not jealous, but I'd be lying.",
		"goals": [{"type": "tame", "ids": ["allo"], "count": 1}], "reward": {"ancient_coin": 20}},
	{"id": "warden_deino", "giver": "warden", "line": "warden_taming", "title": "Reed-stalkers", "needs": "region:glassmere",
		"ask": "The bog's pack hunters, the deinonychus: bigger than raptors and cleverer. Net one and win it with meat. It'll never forgive you if you fail.",
		"done": "A deino of your own. I'd keep it away from the dodos.",
		"goals": [{"type": "tame", "ids": ["deino"], "count": 1}], "reward": {"net": 3, "xp:taming": 120}},
	{"id": "warden_egg", "giver": "warden", "line": "warden_young", "title": "Egg thief",
		"ask": "Every beast nests somewhere. Find a nest, take one egg, and don't stop running till its parents give up. Then bring me the tale.",
		"done": "You're still in one piece! Here: an incubator. Set the egg in it and keep it warm.",
		"goals": [{"type": "egg", "count": 1}], "reward": {"incubator": 1}},
	{"id": "warden_hatch", "giver": "warden", "line": "warden_young", "title": "New life", "needs": "milestone:alpha",
		"ask": "Put an egg in a warm incubator, a fire or torch close by, and wait. A baby that hatches in your care thinks you're its mother.",
		"done": "A hatchling! Keep it fed and close. They grow up faster than you'd think.",
		"goals": [{"type": "hatch", "count": 1}], "reward": {"ancient_coin": 8, "berry": 10}},
	{"id": "warden_grow", "giver": "warden", "line": "warden_young", "title": "Raised by hand", "needs": "milestone:alpha",
		"ask": "Raise a baby to full size. Hatch one, or win over a wild one, if you dare get past its mother.",
		"done": "All grown up. You'll never have a more loyal beast than one you raised.",
		"goals": [{"type": "grow", "count": 1}], "reward": {"ancient_coin": 15}},
	{"id": "warden_saddle", "giver": "warden", "line": "warden_riding", "title": "In the saddle",
		"ask": "A stego or a trike will carry you, if you give it a saddle. Make one at the bench (plank, fibre, crystal) and fit it through its companion menu.",
		"done": "Snug as a boot. Now climb up.",
		"goals": [{"type": "saddle", "count": 1}], "reward": {"ancient_coin": 6}},
	{"id": "warden_ride", "giver": "warden", "line": "warden_riding", "title": "Ride out",
		"ask": "Riding's nothing like walking. Spend a good while in the saddle, two minutes all told, and learn how your beast moves.",
		"done": "You sit it like you were born up there!",
		"goals": [{"type": "deed", "id": "ride", "count": 120}], "reward": {"beast_treat": 2, "xp:taming": 80, "perk:calm_voice": 1}},
	{"id": "warden_tend", "giver": "warden", "line": "warden_riding", "title": "Hale and hearty",
		"ask": "Beasts get hurt keeping you safe. Bring your hurt companions to me and I'll patch them up. It's a coin each, and worth it.",
		"done": "There. Good as new. Don't let them bleed out in the wilds.",
		"goals": [{"type": "deed", "id": "tend", "count": 1}], "reward": {"ancient_coin": 3, "xp:taming": 40}},
	# Pass 18: a hunter's saddle (Grimjaw's hide), and wings.
	{"id": "warden_hunter", "giver": "warden", "line": "warden_riding", "title": "A hunter under you", "needs": "milestone:grimjaw",
		"ask": "With Grimjaw's hide you can make a saddle for a hunter: a raptor, an allosaur, even a rex. Tame one, saddle it, and ride it.",
		"done": "Now that's a sight: a keeper on a hunter's back. Mind it doesn't eat the neighbours.",
		"goals": [{"type": "saddle", "count": 2}], "reward": {"bloody_bait": 3, "xp:taming": 150}},
	{"id": "warden_wings", "giver": "warden", "line": "warden_riding", "title": "Wings", "needs": "region:jungle",
		"ask": "The pteranodons of the jungle fish the rivers. Win one over with fish from your own hand, saddle it, and it'll carry you into the sky. Space to take off, E over the jungle to rise into the treetops.",
		"done": "You flew! I watched you go over the trees. I've never been so jealous of anyone.",
		"goals": [{"type": "tame", "ids": ["ptera"], "count": 1}, {"type": "deed", "id": "fly", "count": 60}], "reward": {"ancient_coin": 20, "xp:taming": 200}},

	# Pass 17: Nell, the Brood-Keeper: eggs, hatchlings and bloodlines.
	{"id": "breeder_clutch", "giver": "breeder", "line": "breeder_line", "title": "A clutch of your own",
		"ask": "Eggs, Keeper, eggs! Every nest you find is a family you could raise. Take three eggs from wild nests, and keep running.",
		"done": "Three! You've quick feet. Here, treats for the little ones when they hatch.",
		"goals": [{"type": "egg", "count": 3}], "reward": {"beast_treat": 2, "xp:breeding": 60}},
	{"id": "breeder_warm", "giver": "breeder", "line": "breeder_line", "title": "Warm hands",
		"ask": "An egg wants warmth: an incubator by a fire or a torch. Hatch two of them. The first thing a hatchling sees, it follows forever.",
		"done": "Two little ones! Now you're a mother, of a sort. Take this: another incubator never hurts.",
		"goals": [{"type": "hatch", "count": 2}], "reward": {"incubator": 1, "xp:breeding": 60}},
	{"id": "breeder_raise", "giver": "breeder", "line": "breeder_line", "title": "Grown in your care",
		"ask": "Babies need feeding and keeping close. Raise two of them all the way to full size.",
		"done": "All grown up, and every bit as loyal as I promised. You've a gift.",
		"goals": [{"type": "grow", "count": 2}], "reward": {"ancient_coin": 10, "xp:breeding": 80}},
	{"id": "breeder_pair", "giver": "breeder", "line": "breeder_line", "title": "A pair at home",
		"ask": "Now the real work. Two tame beasts of a kind, kept together at home a while, will lay. Get a pair to lay an egg of their own.",
		"done": "Your own bloodline! Their young take after them both. Pick your pairs well.",
		"goals": [{"type": "deed", "id": "bred", "count": 1}], "reward": {"ancient_coin": 15, "xp:breeding": 120, "perk:breed_warm": 1}},
	{"id": "breeder_raptor", "giver": "breeder", "line": "breeder_line", "title": "A hunter's egg",
		"ask": "Grazers' eggs are easy. A raptor's is another thing: the whole pack guards it. Bring me one, whole.",
		"done": "Still warm! Brave, or mad. Both, I think. Here.",
		"goals": [{"type": "have", "id": "raptor_egg", "count": 1, "take": true}], "reward": {"ancient_coin": 12, "incubator": 1}},
	{"id": "breeder_bloodline", "giver": "breeder", "line": "breeder_line", "title": "A strong bloodline",
		"ask": "One clutch is luck. Three is breeding. Have your pairs lay three times, and watch what their young inherit.",
		"done": "Look at the size of that one! Stronger every generation. That's what I live for.",
		"goals": [{"type": "deed", "id": "bred", "count": 3}], "reward": {"ancient_coin": 20, "xp:breeding": 200}},

	# Pass 17: Harrow, the Delver: stone, ore and bombs.
	{"id": "miner_props", "giver": "miner", "line": "miner_line", "title": "Pit props",
		"ask": "A mine without props is a grave. Bring me twenty stones and I'll shore this place up, and show you a thing or two about swinging a pick.",
		"done": "Solid. You swing like a miner now. Mostly.",
		"goals": [{"type": "have", "id": "stone", "count": 20, "take": true}], "reward": {"torch": 6, "xp:gathering": 60}},
	{"id": "miner_bombs", "giver": "miner", "line": "miner_line", "title": "Powder and crystal",
		"ask": "Want to know a secret? Crush Sky-Fang crystal fine, pack it tight and give it a spark, and it'll blow a hole in anything. Bring me eight shards and I'll show you how.",
		"done": "There: stone, fibre and three shards make two bombs, at any workbench. Throw it and run. Don't hold it. Here, a few to start.",
		"goals": [{"type": "have", "id": "crystal_shard", "count": 8, "take": true}], "reward": {"milestone:learned_bombs": 1, "bomb": 4}},
	{"id": "miner_blast", "giver": "miner", "line": "miner_line", "title": "Blast it",
		"ask": "Now use them. Blow apart rock, ore or those boulders the quakes drop, three times over. Stand well back.",
		"done": "Ha! Music. The sweetest sound under the ground.",
		"goals": [{"type": "deed", "id": "blast", "count": 3}], "reward": {"ancient_coin": 8, "xp:gathering": 100, "perk:gath_pick": 1}},
	{"id": "miner_rust", "giver": "miner", "line": "miner_line", "title": "Rustiron", "needs": "item:rustiron",
		"ask": "Out where the allosaurs hunt, the rock bleeds red: rustiron. Four lumps and I'll make it worth your while.",
		"done": "Good iron, that. The allosaurs sharpen their teeth on it, they say.",
		"goals": [{"type": "have", "id": "rustiron", "count": 4, "take": true}], "reward": {"ancient_coin": 12, "bomb": 4}},
	{"id": "miner_prism", "giver": "miner", "line": "miner_line", "title": "Prism from the deep",
		"ask": "Deep in the crystal seams there's prism: violet, and harder than anything. A power-two pick breaks it. Bring me three.",
		"done": "Look at it catch the light. I've spent my life chasing that colour.",
		"goals": [{"type": "have", "id": "prism_crystal", "count": 3, "take": true}], "reward": {"ancient_coin": 15, "xp:gathering": 150}},
	{"id": "miner_veins", "giver": "miner", "line": "miner_line", "title": "Every vein", "needs": "item:sunstone",
		"ask": "Every far land has its own ore: sunstone in the dunes, ashglass up in the ash, bog iron by the meres. Three of each and you'll know the wilds better than any map.",
		"done": "You've been everywhere. Here: the best I've got, and my thanks.",
		"goals": [{"type": "have", "id": "sunstone", "count": 3, "take": true}, {"type": "have", "id": "ashglass", "count": 3, "take": true}, {"type": "have", "id": "bog_iron", "count": 3, "take": true}], "reward": {"ancient_coin": 30, "bomb": 6, "xp:gathering": 250, "perk:miner": 1}},

	# Pass 17: Rusk, the Old Blade: the fight.
	{"id": "fighter_raptors", "giver": "fighter", "line": "fighter_line", "title": "Steel your nerve",
		"ask": "Raptors hunt in packs and test you. Put five of them down. Roll when they leap (Space), and strike when they land.",
		"done": "You're still standing. Good. Most green Keepers don't last a pack.",
		"goals": [{"type": "defeat", "id": "raptor", "count": 5}], "reward": {"bone_arrow": 20, "xp:combat": 60}},
	{"id": "fighter_bow", "giver": "fighter", "line": "fighter_line", "title": "A string to your bow",
		"ask": "A spear is fine, but a bow keeps the teeth away. Make a Reedwood Bow at the bench, and bone arrows to go with it.",
		"done": "Now you can start a fight from where it can't reach you. That's the whole trick.",
		"goals": [{"type": "craft", "id": "reed_bow", "count": 1}], "reward": {"bone_arrow": 30, "xp:archery": 60}},
	{"id": "fighter_fangs", "giver": "fighter", "line": "fighter_line", "title": "Fanged armour",
		"ask": "Moss won't turn a raptor's claw. Fangbound will: their own fangs, carved into plates over their hides. Make a Fangbound Chestplate.",
		"done": "Wear your enemies. Old hunters' wisdom.",
		"goals": [{"type": "craft", "id": "bone_chestplate", "count": 1}], "reward": {"ancient_coin": 8, "xp:combat": 60}},
	{"id": "fighter_hunts", "giver": "fighter", "line": "fighter_line", "title": "Thirty hunts",
		"ask": "Every beast fights its own way. Learn them. Bring down thirty, any kind, and you'll know more than I can tell you.",
		"done": "Thirty. You're a hunter now, whatever you were before.",
		"goals": [{"type": "kills", "count": 30}], "reward": {"ancient_coin": 10, "xp:combat": 120, "perk:hardened": 1}},
	{"id": "fighter_allo", "giver": "fighter", "line": "fighter_line", "title": "The rust-backed hunter",
		"ask": "An allosaur waits in cover and comes out of nowhere. Beat one, and you've beaten the thing that ate my brother.",
		"done": "It's done, then. Thank you, Keeper. Truly.",
		"goals": [{"type": "defeat", "id": "allo", "count": 1}], "reward": {"ancient_coin": 12, "xp:combat": 100}},
	{"id": "fighter_scarhorn", "giver": "fighter", "line": "fighter_line", "title": "The Scarhorn", "needs": "species:carno",
		"ask": "The Scarhorn runs its prey down in the dunes: the fastest big hunter alive. Don't run. Roll, and strike its flank.",
		"done": "You outlasted the Scarhorn! I'd buy you a drink, if there were any out here.",
		"goals": [{"type": "defeat", "id": "carno", "count": 1}], "reward": {"ancient_coin": 20, "xp:combat": 150}},
	{"id": "fighter_rex", "giver": "fighter", "line": "fighter_line", "title": "Apex",
		"ask": "There's only one left. The tyrant. Crystal-grown, as long as a longneck, and it knows you're coming. Bring it down.",
		"done": "The Emerald Tyrant... I never thought I'd see the day. There's nothing left out there that should frighten you.",
		"goals": [{"type": "defeat", "id": "rex", "count": 1}], "reward": {"ancient_coin": 30, "trex_scale": 2, "xp:combat": 250, "perk:second_wind": 1}},
]


static func by_id(id: String) -> Dictionary:
	for q in QUESTS:
		if q.id == id: return q
	return {}


static func for_giver(giver: String) -> Array:
	return QUESTS.filter(func(q): return q.giver == giver)


## A task's line (its giver's, for a task without one).
static func line_of(q: Dictionary) -> String:
	return str(q.get("line", q.get("giver", "")))


## A giver's lines, in the order they're first given.
static func lines_for(giver: String) -> Array:
	var out: Array = []
	for q in for_giver(giver):
		var line := line_of(q)
		if not line in out: out.append(line)
	return out
